#!/bin/sh

# ____  ____
#/ ___||  _ \  BSPWM CONFIGURATION FILE 
#\___ \| | | | email:roriaxber@gmail.com
# ___) | |_| | website/blog: https://razoriwebsite.neocities.org/
#|____/|____/  github: https://github.com/sirdamian/

#AUTOSTART
xsetroot -cursor_name left_ptr
picom -C &
mpd &
sxhkd &
~/.fehbg &
notify-send "BSPWM Loaded" "Wallpaper Changed!" &
~/.config/polybar/launch.sh &
xrdb -load ~/.Xresources &

#MONITORS
#6 desktops are enough

bspc monitor -d I II III IV V VI 

#-.-.-.-.-CONFIGURATION-.-.-.-.-#

#configurations are beautiful

bspc config border_radius      	 8
bspc config border_width         4
bspc config window_gap          10

bspc config single_monocle		false
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config pointer_follows_monitor	true
bspc config center_pseudo_tiled		true

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme	spiral 
bspc config initial_polarity	first_child
bspc config directional_focus_tightness  high

bspc config top_padding		0
bspc config bottom_padding	0
bspc config left_padding	20
bspc config right_padding	20

bspc config ignore_ewmh_focux   true
bspc config pointer_modifier	mod1

#------Open-Border-Colors-----#

#Its a nerd joke, you wont understand it unless you research about politics XD

bspc config normal_border-color        "#2E3440"
bspc config focused_border_color       "#D8DEE9"

#------Rules-Of-My-Computer-----#

#Rules that are followed, everything has rules, even window managers!

bspc rule -a mpv state=fullscreen
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
